name: "redis-starter-go"
services:
  redis:
    container_name: redis
    image: "redis/redis-stack-server:latest"
    ports:
      - 6381:6379
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - redis-data:/data
 
  server:
    container_name: server
    build: .
    ports:
      - "${PORT}:${PORT}"
    environment:
      PORT: ${PORT}
    env_file:
      - .env
      - .env.docker
    restart: always
    depends_on:
      - redis

  test:
    build: .
    command: go test ./... -v
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis

volumes:
  redis-data:
