name: Go + Docker

on:
  push:
    branches: ["main"]
    # For releases:
    tags:
      - "v*.*.*"
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

  docker:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:latest .
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            TAG=$(echo "${GITHUB_REF}" | sed 's|refs/tags/||')
            docker tag ghcr.io/${{ github.repository }}:latest ghcr.io/${{ github.repository }}:${TAG}
          fi

      - name: Push Docker image (latest)
        run: docker push ghcr.io/${{ github.repository }}:latest

      - name: Push Docker image (tag)
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG=$(echo "${GITHUB_REF}" | sed 's|refs/tags/||')
          docker push ghcr.io/${{ github.repository }}:${TAG}
